feat/bazel: `//cmd/{frontend,server}` targets that don't include client bundle for backend integration tests (#62877)
Currently, all backend integration tests transitively depend on the client bundle. This results in rebuilds of the closure, and a (likely) cache miss on the test, when modifying any client-side files. 
Given that the client bundle isnt needed for these tests, we can create targets that don't include the client bundle in its transitive closure, which should in theory improve the cache hit for backend integration tests by not having client side changes invalidate it. This would also be beneficial in local env, to keep frontend rebuilds down

To do this, we still need to create a `web.manifest.json` file due to some unfortunate requirement on that file existing as part of initializing the sourcegraph instance. For this I just create an empty json file, `select` this instead of the client bundle target in client/web/dist/BUILD.bazel based on a `//:integration_testing_enabled` config setting, and creating a `go_binary`-wrapping bazel rule + macro that automatically applies a transition to set this to true `go_binary_nobundle`, and using that rule for the specific `//cmd/{server,frontend}:{server,frontend}_nobundle` binary rules (along with the relevant `oci_{image,tarball}` etc rules to consume it).



## Test plan

- Integration tests in CI still work
- `bazel cquery 'kind("js_library", deps(//cmd/frontend:image_nobundle))'`, `bazel cquery 'kind("js_library", deps(//cmd/server:image_nobundle))'`, ``bazel cquery 'kind("js_library", deps(//testing:backend_integration_test))'` etc  all return empty set
- Release test with marker in web bundle to ensure released images contain the web bundle via `sg release run test --version 5.4.2` (commenting out other tests for brevity)

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -91,6 +91,33 @@ test:
           echo "❌ Tag '{{version}}' already exists"
           exit 1
         fi
+    - name: 'check:frontend and server image contain bundle'
+      cmd: |
+        set -eu
+
+        REGISTRY="${PROD_REGISTRY:-''}"
+
+        # the reason this is not in the requirements check of the release yaml is because those checks also
+        # apply when running the release tooling locally, and the testing steps are supposed to run in CI
+        if [ -z ${REGISTRY} ]; then
+          echo "PROD_REGISTRY is not set - unable to check frontend/server image"
+          exit 1
+        fi
+
+        for image in frontend server; do
+          IMAGE="${REGISTRY}/$image:{{tag}}"
+
+          # Pull the image so that we can inspect it
+          echo "pulling $image image ${IMAGE}"
+          # docker pull "${IMAGE}"
+
+          echo "checking $image binary in $image image for web bundle"
+          marker=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "strings $image | grep WEB_BUNDLE" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+          if [[ "$marker" != '"_marker": "WEB_BUNDLE"' ]]; then
+            echo "$image:{{tag}} does not contain the web bundle marker string: '$marker'"
+            exit 1
+          fi
+        done
     - name: 'check:migrator-schemas'
       cmd: |
         set -eu
