Remove QA things

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -17,8 +17,8 @@ requirements:
 
   # #bolaji-release-testing
   # https://start.1password.com/open/i?a=HEDEDSLHPBFGRBTKAKJWE23XX4&v=isv4abynddpox72wwbhaamo76e&i=7zjax5rm5hlilbgrzeb257i62i&h=team-sourcegraph.1password.com
-  # - name: 'Slack Webhook URL'
-  #   env: SLACK_WEBHOOK_URL
+  - name: 'Slack Webhook URL'
+    env: SLACK_WEBHOOK_URL
 
 internal:
   create:
@@ -64,49 +64,49 @@ internal:
 
 test:
   steps:
-    # - name: 'check:git tag does not exist'
-    #   cmd: |
-    #     tags=$(git ls-remote --tags origin | sort -t '/' -k 3 | cut -f 2 | awk -F '/' '{gsub(/\^\{\}$/, "", $3); print $3}' | uniq)
-    #     if echo "${tags}" | grep -q "^{{version}}$"; then
-    #       echo "❌ Tag '{{version}}' already exists"
-    #       exit 1
-    #     fi
-    # - name: 'check:migrator-schemas'
-    #   cmd: |
-    #     set -eu
+    - name: 'check:git tag does not exist'
+      cmd: |
+        tags=$(git ls-remote --tags origin | sort -t '/' -k 3 | cut -f 2 | awk -F '/' '{gsub(/\^\{\}$/, "", $3); print $3}' | uniq)
+        if echo "${tags}" | grep -q "^{{version}}$"; then
+          echo "❌ Tag '{{version}}' already exists"
+          exit 1
+        fi
+    - name: 'check:migrator-schemas'
+      cmd: |
+        set -eu
 
-    #     REGISTRY="${PROD_REGISTRY:-''}"
+        REGISTRY="${PROD_REGISTRY:-''}"
 
-    #     # the reason this is not in the requirements check of the release yaml is because those checks also
-    #     # apply when running the release tooling locally, and the testing steps are supposed to run in CI
-    #     if [ -z ${REGISTRY} ]; then
-    #       echo "PROD_REGISTRY is not set - unable to check migrator image"
-    #       exit 1
-    #     fi
+        # the reason this is not in the requirements check of the release yaml is because those checks also
+        # apply when running the release tooling locally, and the testing steps are supposed to run in CI
+        if [ -z ${REGISTRY} ]; then
+          echo "PROD_REGISTRY is not set - unable to check migrator image"
+          exit 1
+        fi
 
-    #     IMAGE="${REGISTRY}/migrator:{{tag}}"
+        IMAGE="${REGISTRY}/migrator:{{tag}}"
 
-    #     # Pull the image so that we can inspect it
-    #     echo "pulling migrator image ${IMAGE}"
-    #     docker pull "${IMAGE}"
+        # Pull the image so that we can inspect it
+        echo "pulling migrator image ${IMAGE}"
+        docker pull "${IMAGE}"
 
-    #     echo "checking migrator image for {{version}} schema description files"
-    #     # now we check that the schema description files exist
-    #     # we need to trim the result from docker since it has '\r' hence the use of tr
-    #     count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/{{version}}-*.json | wc -l" | tr -d '[:space:]')
-    #     if [[ "$count" -ne 3 ]]; then
-    #       echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected 3 got ${count}"
-    #       exit 1
-    #     fi
+        echo "checking migrator image for {{version}} schema description files"
+        # now we check that the schema description files exist
+        # we need to trim the result from docker since it has '\r' hence the use of tr
+        count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/{{version}}-*.json | wc -l" | tr -d '[:space:]')
+        if [[ "$count" -ne 3 ]]; then
+          echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected 3 got ${count}"
+          exit 1
+        fi
 
-    #     echo "checking migrator image for older schema description files"
-    #     count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/*-internal_database_schema*json | wc -l" | tr -d '[:space:]')
+        echo "checking migrator image for older schema description files"
+        count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/*-internal_database_schema*json | wc -l" | tr -d '[:space:]')
 
-    #     # in our newer releases we have upwards of 300 schema descriptions, so we check that we have at least 300
-    #     if [[ "$count" -lt 300 ]]; then
-    #       echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected more than 300 got ${count}"
-    #       exit 1
-    #     fi
+        # in our newer releases we have upwards of 300 schema descriptions, so we check that we have at least 300
+        if [[ "$count" -lt 300 ]]; then
+          echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected more than 300 got ${count}"
+          exit 1
+        fi
     - name: 'db:migration:coherence_test'
       cmd: |
         set -eu
