update

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -84,28 +84,27 @@ promoteToPublic:
           fi
   finalize:
     steps:
-      - name: "Register on release registry"
+      - name: "Promote on release registry"
         cmd: |
           echo "pretending to call release registry api"
+
+      # tag is usually in the format `5.3.2`
+      # while version is usually the tag prepended with a v, `v5.3.2`
       - name: "Slack notification (#announce-engineering)"
         cmd: |
           echo "Posting slack notification for release"
-            body=$(curl -s --fail-with-body -X POST "$SLACK_WEBHOOK_URL" -H "Content-Type: application/json" -d '{
-                "text": |
-                  "*Sourcegraph 5.3.2 has been published*
+          changelog_version="${tag//./}"
+          body=$(curl -s --fail-with-body -X POST "$SLACK_WEBHOOK_URL" -H "Content-Type: application/json" -d '{
+            "text": "*Sourcegraph {{tag}} has been published*\n\n* [Changelog](https://sourcegraph.com/docs/CHANGELOG#${changelog_version})\n* [GitHub release](https://github.com/sourcegraph/sourcegraph/releases/tag/{{version}})"
+          }')
+          exit_code=$?
 
-                  * [Changelog](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#5-3-2)
-                  * [GitHub release](https://github.com/sourcegraph/sourcegraph/releases/tag/v5.3.2)"
-              }')
-            exit_code=$?
-
-            if [ $exit_code != 0 ]; then
-              echo "❌ Failed to create build on Buildkite, got:"
-              echo "--- raw body ---"
-              echo $body
-              echo "--- raw body ---"
-              exit $exit_code
-            else
-              echo "Build created, see:"
-              echo $body | jq .web_url
-            fi
+          if [ $exit_code != 0 ]; then
+            echo "❌ Unable to post message to slack, got:"
+            echo "--- raw body ---"
+            echo $body
+            echo "--- raw body ---"
+            exit $exit_code
+          else
+            echo "Posted to slack."
+          fi
