poc(rel): attempt at plugging upgradetest into rel tests

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -1,8 +1,8 @@
 meta:
   productName: sourcegraph
-  repository: "github.com/sourcegraph/sourcegraph"
+  repository: 'github.com/sourcegraph/sourcegraph'
   owners:
-    - "@sourcegraph/release"
+    - '@sourcegraph/release'
 
 requirements:
   - name: "curl"
@@ -17,14 +17,14 @@ requirements:
 
   # #bolaji-release-testing
   # https://start.1password.com/open/i?a=HEDEDSLHPBFGRBTKAKJWE23XX4&v=isv4abynddpox72wwbhaamo76e&i=7zjax5rm5hlilbgrzeb257i62i&h=team-sourcegraph.1password.com
-  - name: "Slack Webhook URL"
+  - name: 'Slack Webhook URL'
     env: SLACK_WEBHOOK_URL
 
 internal:
   create:
     steps:
       patch:
-        - name: "buildkite"
+        - name: 'buildkite'
           cmd: |
             echo "Triggering build on sourcegraph/sourcegraph with VERSION={{version}} on branch {{git.branch}}"
             body=$(curl -s --fail-with-body -X POST "https://api.buildkite.com/v2/organizations/sourcegraph/pipelines/sourcegraph/builds" -H "Content-Type: application/json" -H "Authorization: Bearer $BUILDKITE_ACCESS_TOKEN" -d '{
@@ -50,10 +50,10 @@ internal:
             fi
   finalize:
     steps:
-      - name: "Register on release registry"
+      - name: 'Register on release registry'
         cmd: |
           echo "pretending to call release registry api"
-      - name: "notifications"
+      - name: 'notifications'
         cmd: |
           set -eu
 
@@ -64,54 +64,57 @@ internal:
 
 test:
   steps:
-    - name: "check:git tag does not exist"
+    # - name: 'check:git tag does not exist'
+    #   cmd: |
+    #     tags=$(git ls-remote --tags origin | sort -t '/' -k 3 | cut -f 2 | awk -F '/' '{gsub(/\^\{\}$/, "", $3); print $3}' | uniq)
+    #     if echo "${tags}" | grep -q "^{{version}}$"; then
+    #       echo "❌ Tag '{{version}}' already exists"
+    #       exit 1
+    #     fi
+    # - name: 'check:migrator-schemas'
+    #   cmd: |
+    #     set -eu
+
+    #     REGISTRY="${PROD_REGISTRY:-''}"
+
+    #     # the reason this is not in the requirements check of the release yaml is because those checks also
+    #     # apply when running the release tooling locally, and the testing steps are supposed to run in CI
+    #     if [ -z ${REGISTRY} ]; then
+    #       echo "PROD_REGISTRY is not set - unable to check migrator image"
+    #       exit 1
+    #     fi
+
+    #     IMAGE="${REGISTRY}/migrator:{{tag}}"
+
+    #     # Pull the image so that we can inspect it
+    #     echo "pulling migrator image ${IMAGE}"
+    #     docker pull "${IMAGE}"
+
+    #     echo "checking migrator image for {{version}} schema description files"
+    #     # now we check that the schema description files exist
+    #     # we need to trim the result from docker since it has '\r' hence the use of tr
+    #     count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/{{version}}-*.json | wc -l" | tr -d '[:space:]')
+    #     if [[ "$count" -ne 3 ]]; then
+    #       echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected 3 got ${count}"
+    #       exit 1
+    #     fi
+
+    #     echo "checking migrator image for older schema description files"
+    #     count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/*-internal_database_schema*json | wc -l" | tr -d '[:space:]')
+
+    #     # in our newer releases we have upwards of 300 schema descriptions, so we check that we have at least 300
+    #     if [[ "$count" -lt 300 ]]; then
+    #       echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected more than 300 got ${count}"
+    #       exit 1
+    #     fi
+    - name: 'db:migration:coherence_test'
       cmd: |
-        tags=$(git ls-remote --tags origin | sort -t '/' -k 3 | cut -f 2 | awk -F '/' '{gsub(/\^\{\}$/, "", $3); print $3}' | uniq)
-        if echo "${tags}" | grep -q "^{{version}}$"; then
-          echo "❌ Tag '{{version}}' already exists"
-          exit 1
-        fi
-    - name: "check:migrator-schemas"
-      cmd: |
-        set -eu
-
-        REGISTRY="${PROD_REGISTRY:-''}"
-
-        # the reason this is not in the requirements check of the release yaml is because those checks also
-        # apply when running the release tooling locally, and the testing steps are supposed to run in CI
-        if [ -z ${REGISTRY} ]; then
-          echo "PROD_REGISTRY is not set - unable to check migrator image"
-          exit 1
-        fi
-
-        IMAGE="${REGISTRY}/migrator:{{tag}}"
-
-        # Pull the image so that we can inspect it
-        echo "pulling migrator image ${IMAGE}"
-        docker pull "${IMAGE}"
-
-        echo "checking migrator image for {{version}} schema description files"
-        # now we check that the schema description files exist
-        # we need to trim the result from docker since it has '\r' hence the use of tr
-        count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/{{version}}-*.json | wc -l" | tr -d '[:space:]')
-        if [[ "$count" -ne 3 ]]; then
-          echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected 3 got ${count}"
-          exit 1
-        fi
-
-        echo "checking migrator image for older schema description files"
-        count=$(docker run -t --rm --entrypoint /bin/sh "${IMAGE}" -c "ls -al /schema-descriptions/*-internal_database_schema*json | wc -l" | tr -d '[:space:]')
-
-        # in our newer releases we have upwards of 300 schema descriptions, so we check that we have at least 300
-        if [[ "$count" -lt 300 ]]; then
-          echo "migrator:{{tag}} does not contain the correct amount of schema description files for this release - expected more than 300 got ${count}"
-          exit 1
-        fi
+        bazel run //testing/tools/upgradetest:sh_upgrade_test -- std
 
 promoteToPublic:
   create:
     steps:
-      - name: "buildkite"
+      - name: 'buildkite'
         cmd: |
           # We set DISABLE_ASPECT_WORKFLOWS to true, because the promotion is purely about retagging images
           # and we don't rely on AW at all.
@@ -140,10 +143,10 @@ promoteToPublic:
           fi
   finalize:
     steps:
-      - name: "Promote on release registry"
+      - name: 'Promote on release registry'
         cmd: |
           echo "pretending to call release registry api"
-      - name: "git:tag"
+      - name: 'git:tag'
         cmd: |
           set -eu
 
@@ -159,7 +162,7 @@ promoteToPublic:
           EOF
       # tag is usually in the format `5.3.2`
       # while version is usually the tag prepended with a v, `v5.3.2`
-      - name: "Slack notification (#announce-engineering)"
+      - name: 'Slack notification (#announce-engineering)'
         cmd: |
           echo "Posting slack notification for release"
           tag="{{tag}}"
