Update manifests to post Slack messages on internal releases and public promotions (#61196)
* add slack message

* update

* update

* remove script

* Update release.yaml

Co-authored-by: William Bezuidenhout <william.bezuidenhout@sourcegraph.com>

* Update release.yaml

Co-authored-by: William Bezuidenhout <william.bezuidenhout@sourcegraph.com>

---------

Co-authored-by: William Bezuidenhout <william.bezuidenhout@sourcegraph.com>

diff --git a/release.yaml b/release.yaml
--- a/release.yaml
+++ b/release.yaml
@@ -9,6 +9,8 @@ requirements:
     cmd: "curl --help"
   - name: "Buidkite access token"
     env: BUILDKITE_ACCESS_TOKEN
+  - name: "Slack Webhook URL"
+    env: SLACK_WEBHOOK_URL
 
 internal:
   create:
@@ -82,6 +84,28 @@ promoteToPublic:
           fi
   finalize:
     steps:
-      - name: "Register on release registry"
+      - name: "Promote on release registry"
         cmd: |
           echo "pretending to call release registry api"
+
+      # tag is usually in the format `5.3.2`
+      # while version is usually the tag prepended with a v, `v5.3.2`
+      - name: "Slack notification (#announce-engineering)"
+        cmd: |
+          echo "Posting slack notification for release"
+          tag="{{tag}}"
+          changelog_version="${tag//./}"
+          body=$(curl -s --fail-with-body -X POST "$SLACK_WEBHOOK_URL" -H "Content-Type: application/json" -d '{
+            "text": "*Sourcegraph {{tag}} has been published*\n\n* [Changelog](https://sourcegraph.com/docs/CHANGELOG#${changelog_version})\n* [GitHub release](https://github.com/sourcegraph/sourcegraph/releases/tag/{{version}})"
+          }')
+          exit_code=$?
+
+          if [ $exit_code != 0 ]; then
+            echo "❌ Unable to post message to slack, got:"
+            echo "--- raw body ---"
+            echo $body
+            echo "--- raw body ---"
+            exit $exit_code
+          else
+            echo "Posted to slack."
+          fi
