Automatic workspace discovery (#442)
* Implement dynamic workspace discovery

* update schema and fix template helpers

* Add changelog entry

* Rename file

* Change naming

* Use strings.ReplaceAll

diff --git a/internal/campaigns/testdata/dummydocker/docker b/internal/campaigns/testdata/dummydocker/docker
--- a/internal/campaigns/testdata/dummydocker/docker
+++ b/internal/campaigns/testdata/dummydocker/docker
@@ -9,6 +9,8 @@
 
 dummy_temp_file="DUMMYDOCKER-TEMP-FILE"
 
+workdir_prefix="/work/"
+
 if [[ "${1}" == "run" ]]; then
     last_arg="${@: -1}"
 
@@ -24,19 +26,43 @@ if [[ "${1}" == "run" ]]; then
         # If the last arg is the temp file we "created" earlier, we now want to
         # execute it.
         #
-        # But the real script is in the matching host temp file, which should
+        # We iterate over the arguments to find the things we're interested in:
+        #
+        # 1. The `--workdir [dir]` parameters
+        # 2. The script that we need to execute
+        #
+        # We need (1) to execute (2) in the correct subfolder.
+        # And (2) is in the in the matching host temp file, which should
         # be mounted into the temp file inside the container.
         #
         # We need to find it in the args and then execute it.
 
+        workdirUpcoming=""
+        workdir=""
         host_temp_file=""
         for i in "$@";
         do
+          if [[ ! -z "${workdirUpcoming}" ]]; then
+            workdir="${i}"
+            workdirUpcoming=""
+          fi
+          if [[ ${i} =~ ^--workdir$ ]]; then
+            workdirUpcoming="yes"
+          fi
+
           if [[ ${i} =~ ^type=bind,source=(.*),target=${dummy_temp_file},ro$ ]]; then
             host_temp_file="${BASH_REMATCH[1]}"
           fi
         done
         [ -z "$host_temp_file" ] && echo "host temp file not found in args" && exit 1;
+        [ -z "$workdir" ] && echo "workdir not found in args" && exit 1;
+
+        # Let's strip the prefix off the workdir
+        relative_workdir="${workdir#"${workdir_prefix}"}"
+        # If the non-prefixed version is not blank, then we need to `cd` into it
+        if [[ ! -z "${relative_workdir}" ]]; then
+          cd "${relative_workdir}"
+        fi
 
         # Now that we have the path to the host temp file, we can execute it
         exec bash ${host_temp_file}
