Trick around docker install

diff --git a/.github/workflows/sg-testing.yml b/.github/workflows/sg-testing.yml
--- a/.github/workflows/sg-testing.yml
+++ b/.github/workflows/sg-testing.yml
@@ -39,30 +39,37 @@ jobs:
           . ~/.bashrc
           sg -y setup
 
+      # - name: installing Docker
+      #   run: |
+      #     mkdir -p ~/.docker/machine/cache
+      #     curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
+      #     brew install docker docker-machine
+
       - name: run setup commands manually
         run: |
           set -x
-          brew install --cask docker
-          brew install git gnu-sed comby pcre sqlite jq
-          # brew install go yarn node # skipping those to avoid clashing with what's already present on the VM
-          brew install postgres redis
-          brew services start postgresql
-          brew services start redis
-          (hash psql && echo "OK") || echo "NOT OK"
-          . ~/.bash_profile 
-          which psql
-          NVM_VERSION="$(curl https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r .name)"
-          curl -L https://raw.githubusercontent.com/nvm-sh/nvm/"$NVM_VERSION"/install.sh -o /tmp/install-nvm.sh
-          sh /tmp/install-nvm.sh 
-          export NVM_DIR="$HOME/.nvm"
-          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-          nvm install
-          # nvm use --delete-prefix # <- this fails, not sure why
-          createdb
-          createuser --superuser sourcegraph
-          psql -c "ALTER USER sourcegraph WITH PASSWORD 'sourcegraph';"
-          createdb --owner=sourcegraph --encoding=UTF8 --template=template0 sourcegraph
-          sudo ./dev/add_https_domain_to_hosts.sh
+          brew install docker --cask
+          sudo /Applications/Docker.app/Contents/MacOS/Docker
+          # brew install git gnu-sed comby pcre sqlite jq
+          # # brew install go yarn node # skipping those to avoid clashing with what's already present on the VM
+          # brew install postgres redis
+          # brew services start postgresql
+          # brew services start redis
+          # (hash psql && echo "OK") || echo "NOT OK"
+          # . ~/.bash_profile 
+          # which psql
+          # NVM_VERSION="$(curl https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r .name)"
+          # curl -L https://raw.githubusercontent.com/nvm-sh/nvm/"$NVM_VERSION"/install.sh -o /tmp/install-nvm.sh
+          # sh /tmp/install-nvm.sh 
+          # export NVM_DIR="$HOME/.nvm"
+          # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+          # nvm install
+          # # nvm use --delete-prefix # <- this fails, not sure why
+          # createdb
+          # createuser --superuser sourcegraph
+          # psql -c "ALTER USER sourcegraph WITH PASSWORD 'sourcegraph';"
+          # createdb --owner=sourcegraph --encoding=UTF8 --template=template0 sourcegraph
+          # sudo ./dev/add_https_domain_to_hosts.sh
           # ./dev/caddy.sh trust 
 
       - name: run sg doctor
